export const API_PATH = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    me: '/auth/me',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  products: {
    list: '/products',
    detail: '/products/{param1}',
    byCategory: '/products/category/{param1}',
    byBrand: '/products/brand/{param1}',
    search: '/products/search',
    create: '/products',
    update: '/roducts/{param1}',
    delete: '/products/{param1}',
  },
  categories: {
    list: '/categories',
    create: '/categories',
    update: '/categories/{param1}',
    delete: '/categories/{param1}',
  },
  brands: {
    list: '/brands',
    create: '/brands',
    update: '/brands/{param1}',
    delete: '/brands/{param1}',
  },
  cart: {
    get: '/cart',
    addItem: '/cart/items',
    updateItem: '/cart/items/{param1}',
    removeItem: '/cart/items/{param1}',
    clear: '/cart',
  },
  orders: {
    place: '/orders',
    my: '/orders',
    detail: '/orders/{param1}',
    track: '/orders/{param1}/track',
    adminAll: '/orders/admin/all',
    adminUpdateStatus: '/orders/admin/{param1}/status',
  },
  wishlist: {
    get: '/wishlist',
    add: '/wishlist/{param1}',
    remove: '/wishlist/{param1}',
  },
  reviews: {
    byProduct: '/reviews/product/{param1}',
    create: '/reviews',
    delete: '/reviews/{param1}',
  },
  inventory: {
    lowStock: '/admin/inventory/low-stock',
    update: '/admin/inventory/{param1}',
  },
  admin: {
    products: '/admin/products',
  },
  support: {
    create: '/tickets',
    my: '/tickets',
    detail: '/tickets/{param1}',
    reply: '/tickets/{param1}/reply',
    adminAll: '/tickets/admin/all',
    adminUpdateStatus: '/tickets/admin/{param1}/status',
    adminAssign: '/tickets/admin/{param1}/assign',
  },
  payments: {
    createIntent: '/payments/create-intent',
  },
};
